# Generated by Django 6.0.3 on 2026-03-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Paid", "Paid")],
                default="Pending",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("Payment", "Payment"), ("Fine", "Fine")],
                default="Payment",
                max_length=8,
            ),
        ),
    ]
