# Generated by Django 6.0.3 on 2026-03-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_status_alter_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.TextField(),
        ),
    ]
