# Generated by Django 6.0.3 on 2026-03-28 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_daily_fee'),
        ('borrowings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='borrowing',
            name='actual_return_date_valid',
        ),
        migrations.AddConstraint(
            model_name='borrowing',
            constraint=models.CheckConstraint(condition=models.Q(('actual_return_date__isnull', True), ('actual_return_date__gte', models.F('borrow_date')), _connector='OR'), name='actual_return_date_valid'),
        ),
    ]
